### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by JeSciglio** [thuml/Anomaly-Transformer#74]
installed: python3.6.13  cuda10.2 pytorch1.8.0
torch.cuda.is_available(): True

but:
RuntimeError: No CUDA GPUs are available

How can i solve this problem?Thank you very much!

**Comment by makabaka22** [comment]
Check the ID of the GPU, and then go to the `.sh` file for the corresponding dataset in the `scripts/` directory and change the `export CUDA_VISIBLE_DEVICES=0` to your own GPU's ID.

**Comment by pokerface-cyz** [comment]
pytorch版本太高了，手动降为1.4.0就好了

**Comment by aacwx** [comment]
我遇到同样问题，Debug之后发现作者的code似乎使用过多GPU训练或者GPU编号并非从0开始，在复现时如果单卡训练的话就会报错，需要自己修改/scripts下的启动脚本export CUDA_VISIBLE_DEVICES=your_own_GPUid
